FROM hub.docker.alibaba-inc.com/tre-ai-infra/amd:alinux3_sglang_0408_containerd_accelerated

ENV LD_LIBRARY_PATH=/usr/local/lib/python3.10/dist-packages/torch/lib:/usr/local/nvidia/lib64:/usr/lib64:/usr/local/cuda/lib64:$LD_LIBRARY_PATH

WORKDIR /opt/sglang

COPY . .

RUN ls -rlt /opt/sglang

# 安装依赖包并缓存结果
RUN /usr/local/bin/pip3.10 install -r requirements/alibaba.txt -i https://artifacts.antgroup-inc.cn/simple/ \
     --extra-index-url=http://artlab.alibaba-inc.com/1/pypi/aios-ai-infra \
     --extra-index-url=https://artlab.alibaba-inc.com/1/PYPI/py-central/ \
     --extra-index-url=https://artlab.alibaba-inc.com/1/PYPI/pytorch/ \
     --extra-index-url=http://artlab.alibaba-inc.com/1/pypi/rtp_diffusion \
     --trusted-host=artlab.alibaba-inc.com \
     --find-links https://flashinfer.ai/whl/cu121/torch2.5/flashinfer-python/ \
     && rm -rf ~/.cache/pip

     #--extra-index-url=https://rtp-pypi-mirrors.alibaba-inc.com/root/pypi/+simple \


WORKDIR /app/sglang_server

COPY whale_sglang .

RUN chmod -R 777 .

RUN mkdir /.cache
RUN chmod -R 777 /.cache

RUN mkdir /.triton
RUN chmod -R 777 /.triton

RUN mkdir /.config

RUN chmod -R 777 /.config

RUN mkdir /.aiter

RUN chmod -R 777 /.aiter

RUN chmod -R 777  /tmp/aiter_configs

# 从 OSS 下载预编译的 aiter JIT so 文件
RUN mkdir -p /opt/aiter/aiter/jit/ && \
    curl -fsSL -o /opt/aiter/aiter/jit/mha_batch_prefill_bf16_nlogits_nbias_mask_nlse_ndropout_nqscale.so \
        https://434934.oss-cn-hangzhou-zmf.aliyuncs.com/wenhua/mha_batch_prefill_bf16_nlogits_nbias_mask_nlse_ndropout_nqscale.so && \
    curl -fsSL -o /opt/aiter/aiter/jit/mha_varlen_fwd_bf16_nlogits_nbias_nmask_nlse_ndropout_nskip_nqscale.so \
        https://434934.oss-cn-hangzhou-zmf.aliyuncs.com/wenhua/mha_varlen_fwd_bf16_nlogits_nbias_nmask_nlse_ndropout_nskip_nqscale.so && \
    curl -fsSL -o /opt/aiter/aiter/jit/module_norm.so \
        https://434934.oss-cn-hangzhou-zmf.aliyuncs.com/wenhua/module_norm.so

RUN chmod -R 777 /opt



# Patch PyTorch to also catch PermissionError when calling nvcc (happens for non-root users)
RUN sed -i \
    's/except (FileNotFoundError, subprocess.CalledProcessError):/except (FileNotFoundError, subprocess.CalledProcessError, PermissionError):/' \
    /usr/local/lib/python3.10/site-packages/torch/_dynamo/debug_utils.py




RUN ls -rlt /opt

RUN ls -rlt /app/sglang_server
